### PR TITLE
Added Compatibility with other mods

### PR DESCRIPTION
**Pull request by AlexKage69**
Removed Hestia. (*Hestia mod should add to CodexMenu)
Added access to RealGodNames for compatibility with other mods.
Added Pages to Duos under Dusa.
Added more specific name for
BoonTable -> CodexBoonTable

*Apollo mod is coming on and I changed the CodexMenu to support external god. I need to have access to RealGodNames (Using ModUtil) and to support more than 28 Duos. 

Thanks.

### CODE REVIEW

**Comment by PonyWarrior** [comment]
I've replied to you on discord.

**Comment by AlexKage69** [comment]
Changes are going to be made by PonyWarrior.

**Comment by PonyWarrior** [comment]
Not great at using github, I cherry picked your commit and merged it. Changed the duo display to support infinite boons with the pager magic made. I'll close this once you've confirmed everything works for you.

**Comment by AlexKage69** [comment]
I tested CodexMenu with Infinite Duos and it works. The only thing is that the Name of new Duos is White. Either it needs a check to changed them the Duo Green, or you did that intentionally to differentiate Original from Mod Duos. Let me know. Other than that, Thanks for the modification on CodexMenu

**Comment by PonyWarrior** [comment]
For swift answers ping me on discord. The white color is the default color used, which means theres an issue with external addition of duos. Could you post or link the code responsible for interaction with codex menu?

**Pull request closed without merging**
